// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4FrYHGG2Ea20tpwW4fqlZU1EWkHzmlA',
    appId: '1:530756935672:web:10edbb4e46b73e2dbd800d',
    messagingSenderId: '530756935672',
    projectId: 'hulak-ko-chitthi',
    authDomain: 'hulak-ko-chitthi.firebaseapp.com',
    storageBucket: 'hulak-ko-chitthi.firebasestorage.app',
    measurementId: 'G-FHG4100CPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJj9MdBtEEmNKD7VA3VV-J-MAZHUQ9RwM',
    appId: '1:530756935672:android:a50eb279b70de2f7bd800d',
    messagingSenderId: '530756935672',
    projectId: 'hulak-ko-chitthi',
    storageBucket: 'hulak-ko-chitthi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgHSuswHXo7Mfufri-7ZP0dl7rMOznNFQ',
    appId: '1:530756935672:ios:2323100a1b770a7bbd800d',
    messagingSenderId: '530756935672',
    projectId: 'hulak-ko-chitthi',
    storageBucket: 'hulak-ko-chitthi.firebasestorage.app',
    iosBundleId: 'com.example.hulakKoChitthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgHSuswHXo7Mfufri-7ZP0dl7rMOznNFQ',
    appId: '1:530756935672:ios:2323100a1b770a7bbd800d',
    messagingSenderId: '530756935672',
    projectId: 'hulak-ko-chitthi',
    storageBucket: 'hulak-ko-chitthi.firebasestorage.app',
    iosBundleId: 'com.example.hulakKoChitthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa4FrYHGG2Ea20tpwW4fqlZU1EWkHzmlA',
    appId: '1:530756935672:web:5bcf2aceede007b0bd800d',
    messagingSenderId: '530756935672',
    projectId: 'hulak-ko-chitthi',
    authDomain: 'hulak-ko-chitthi.firebaseapp.com',
    storageBucket: 'hulak-ko-chitthi.firebasestorage.app',
    measurementId: 'G-6MV339LSS3',
  );

}